name: Daily Weather Email

on:
  schedule:
    # Run every day at 7:00 AM UTC (adjust timezone as needed)
    # Cron format: minute hour day month day-of-week
    # For 7 AM EST (noon UTC), use: '0 12 * * *'
    # For 7 AM PST (3 PM UTC), use: '0 15 * * *'
    - cron: '0 12 * * *'

  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  send-weather-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run weather email script
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        LATITUDE: ${{ secrets.LATITUDE }}
        LONGITUDE: ${{ secrets.LONGITUDE }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
      run: python weather_emailer.py
