name: Daily Weather Email

on:
  schedule:
    # Run every day at 7:00 AM EST/EDT (Eastern Time)
    # Cron format: minute hour day month day-of-week
    # GitHub Actions uses UTC time:
    # - 7 AM EST (winter): 12:00 UTC (EST = UTC-5)
    # - 7 AM EDT (summer): 11:00 UTC (EDT = UTC-4)
    # Using 12:00 UTC for consistent 7 AM EST during winter months
    # Note: Will run at 8 AM during EDT (summer). Adjust to '0 11 * * *' for year-round 7 AM EDT
    - cron: '0 12 * * *'

  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  send-weather-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run weather email script
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        LATITUDE: ${{ secrets.LATITUDE }}
        LONGITUDE: ${{ secrets.LONGITUDE }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
      run: python weather_emailer.py
